apiVersion: v1
kind: Service
metadata:
  name: kubernetes-docker-menu-app-demo
spec:
  selector:
    app: kubernetes-docker-menu-app-demo
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 80
  type: LoadBalancer
status:
  loadBalancer:
    ingress:
    - ip: 146.148.47.155